### ISSUE TITLE
Cannot install AnsibleModule when Mojolicious is version 7.46 (deprecated 'slurp')

### ISSUE THREAD

**Issue by TSheahan** [marcusramberg/AnsibleModule#3]
AnsibleModule  cannot be installed by cpan on systems where Mojolicious version 7.46 is installed.

An error occurs - "slurp" is not exported by the Mojo::Util module

I have lodged a ticket on rt.cpan.org with a workaround for anyone affected now, and a proposed fix:
https://rt.cpan.org/Public/Bug/Display.html?id=123055

**Comment by marcusramberg** [comment]
Thanks, closed in b2a25ee3fb51 - pushed 0.4 to CPAN.
